-- Create the news table to hold external scraped tea market news
CREATE TABLE IF NOT EXISTS public.news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    snippet TEXT,
    sentiment TEXT CHECK (sentiment IN ('bullish', 'bearish', 'neutral')),
    tags JSONB DEFAULT '[]'::JSONB,
    impacts JSONB DEFAULT '[]'::JSONB,
    url TEXT UNIQUE,
    published_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Enable RLS and public read access
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to news"
    ON public.news FOR SELECT
    USING (true);
