-- Prize payout ledger — records money paid OUT to competition winners so the
-- admin finance dashboard shows both funds in and funds out. Admin-gated.

CREATE TABLE IF NOT EXISTS prize_payouts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient    TEXT NOT NULL,
    amount_pence BIGINT NOT NULL CHECK (amount_pence >= 0),
    reason       TEXT,
    method       TEXT,
    paid_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by   UUID REFERENCES auth.users(id),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_prize_payouts_paid_at ON prize_payouts (paid_at DESC);

ALTER TABLE prize_payouts ENABLE ROW LEVEL SECURITY;
-- All access is via the SECURITY DEFINER admin functions below.
REVOKE ALL ON prize_payouts FROM anon, authenticated;

-- ── Record a payout (admin only) ──────────────────────────────────────────
CREATE OR REPLACE FUNCTION admin_record_payout(
    p_recipient    TEXT,
    p_amount_pence BIGINT,
    p_reason       TEXT DEFAULT NULL,
    p_method       TEXT DEFAULT NULL,
    p_paid_at      TIMESTAMPTZ DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_email TEXT;
    v_id    BIGINT;
BEGIN
    SELECT email INTO v_email FROM auth.users WHERE id = auth.uid();
    IF v_email IS DISTINCT FROM 'contact@teatrade.co.uk' THEN
        RETURN jsonb_build_object('success', false, 'error', 'Unauthorized');
    END IF;

    IF p_recipient IS NULL OR length(trim(p_recipient)) = 0 THEN
        RETURN jsonb_build_object('success', false, 'error', 'Recipient is required');
    END IF;
    IF p_amount_pence IS NULL OR p_amount_pence <= 0 THEN
        RETURN jsonb_build_object('success', false, 'error', 'Amount must be greater than zero');
    END IF;

    INSERT INTO prize_payouts (recipient, amount_pence, reason, method, paid_at, created_by)
    VALUES (trim(p_recipient), p_amount_pence, NULLIF(trim(p_reason), ''),
            NULLIF(trim(p_method), ''), COALESCE(p_paid_at, NOW()), auth.uid())
    RETURNING id INTO v_id;

    RETURN jsonb_build_object('success', true, 'id', v_id);
END;
$$;
GRANT EXECUTE ON FUNCTION admin_record_payout(TEXT, BIGINT, TEXT, TEXT, TIMESTAMPTZ) TO authenticated;

-- ── Delete a payout entry (admin only) ───────────────────────────────────
CREATE OR REPLACE FUNCTION admin_delete_payout(p_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_email TEXT;
BEGIN
    SELECT email INTO v_email FROM auth.users WHERE id = auth.uid();
    IF v_email IS DISTINCT FROM 'contact@teatrade.co.uk' THEN
        RETURN jsonb_build_object('success', false, 'error', 'Unauthorized');
    END IF;
    DELETE FROM prize_payouts WHERE id = p_id;
    RETURN jsonb_build_object('success', true);
END;
$$;
GRANT EXECUTE ON FUNCTION admin_delete_payout(BIGINT) TO authenticated;

-- ── Updated finance dashboard: now includes the prize ledger ─────────────
CREATE OR REPLACE FUNCTION admin_finance()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_email    TEXT;
    v_raised   JSONB;
    v_by_month JSONB;
    v_paid     JSONB;
    v_recent   JSONB;
BEGIN
    SELECT email INTO v_email FROM auth.users WHERE id = auth.uid();
    IF v_email IS DISTINCT FROM 'contact@teatrade.co.uk' THEN
        RETURN jsonb_build_object('success', false, 'error', 'Unauthorized');
    END IF;

    -- Funds raised (completed payments) across periods
    SELECT jsonb_build_object(
        'total_pence', COALESCE(SUM(amount_pence), 0),
        'this_month',  COALESCE(SUM(amount_pence) FILTER (WHERE created_at >= DATE_TRUNC('month', NOW())), 0),
        'last_90d',    COALESCE(SUM(amount_pence) FILTER (WHERE created_at >= NOW() - INTERVAL '90 days'), 0),
        'ytd',         COALESCE(SUM(amount_pence) FILTER (WHERE created_at >= DATE_TRUNC('year', NOW())), 0),
        'count',       COUNT(*)
    ) INTO v_raised
    FROM payments
    WHERE status = 'completed';

    -- Monthly revenue breakdown (last 12 months)
    SELECT COALESCE(jsonb_agg(mrow ORDER BY mrow->>'month' DESC), '[]'::jsonb)
    INTO v_by_month
    FROM (
        SELECT jsonb_build_object(
            'month', TO_CHAR(DATE_TRUNC('month', created_at), 'YYYY-MM'),
            'pence', COALESCE(SUM(amount_pence), 0),
            'count', COUNT(*)
        ) AS mrow
        FROM payments
        WHERE status = 'completed'
          AND created_at >= NOW() - INTERVAL '12 months'
        GROUP BY DATE_TRUNC('month', created_at)
    ) m;

    -- Prizes paid OUT across periods
    SELECT jsonb_build_object(
        'total_pence', COALESCE(SUM(amount_pence), 0),
        'this_month',  COALESCE(SUM(amount_pence) FILTER (WHERE paid_at >= DATE_TRUNC('month', NOW())), 0),
        'last_90d',    COALESCE(SUM(amount_pence) FILTER (WHERE paid_at >= NOW() - INTERVAL '90 days'), 0),
        'ytd',         COALESCE(SUM(amount_pence) FILTER (WHERE paid_at >= DATE_TRUNC('year', NOW())), 0),
        'count',       COUNT(*)
    ) INTO v_paid
    FROM prize_payouts;

    -- Recent payout entries (latest 20)
    SELECT COALESCE(jsonb_agg(r ORDER BY (r->>'paid_at') DESC), '[]'::jsonb)
    INTO v_recent
    FROM (
        SELECT jsonb_build_object(
            'id', id,
            'recipient', recipient,
            'amount_pence', amount_pence,
            'reason', reason,
            'method', method,
            'paid_at', paid_at
        ) AS r
        FROM prize_payouts
        ORDER BY paid_at DESC
        LIMIT 20
    ) recent;

    RETURN jsonb_build_object(
        'success', true,
        'generated_at', NOW(),
        'currency', 'GBP',
        'raised', v_raised,
        'by_month', v_by_month,
        'paid_out', v_paid,
        'recent_payouts', v_recent
    );
END;
$$;
GRANT EXECUTE ON FUNCTION admin_finance() TO authenticated;
